config/routes.rb
Secret::Application.routes.draw do
  resources :foos

  get "welcome/index"

  root :to => 'welcome#index'
  
  resources :zecrets, :only => [:create, :show, :find] do
    collection do
      get 'retrieve'
    end
  end

end

app/models/foo.rb
class Foo < ActiveRecord::Base
  attr_accessible :bar
end

app/models/zecret.rb
class Zecret < ActiveRecord::Base
  attr_accessible :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foos }
    end
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
    @foo = Foo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/new
  # GET /foos/new.json
  def new
    @foo = Foo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/1/edit
  def edit
    @foo = Foo.find(params[:id])
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(params[:foo])

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render json: @foo, status: :created, location: @foo }
      else
        format.html { render action: "new" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foos/1
  # PUT /foos/1.json
  def update
    @foo = Foo.find(params[:id])

    respond_to do |format|
      if @foo.update_attributes(params[:foo])
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo = Foo.find(params[:id])
    @foo.destroy

    respond_to do |format|
      format.html { redirect_to foos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @zecret = Zecret.new
  end
end

app/controllers/zecrets_controller.rb
class ZecretsController < ApplicationController
  respond_to :html

  def show
    @zecret = Zecret.find(params[:id])
  end

  def create
    @zecret = Zecret.create(params[:zecret])
    respond_with @zecret
  end

  def retrieve
    @zecret = Zecret.find_by_id(params[:zecret_id])

    if @zecret
      redirect_to @zecret
    else
      flash.alert = "INVALID ZECRET ID!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foos/_form.html.haml
= form_for @foo do |f|
  - if @foo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@foo.errors.count, "error")} prohibited this foo from being saved:"
      %ul
        - @foo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :bar
    = f.text_area :bar
  .actions
    = f.submit 'Save'

app/views/foos/edit.html.haml
%h1 Editing foo

= render 'form'

= link_to 'Show', @foo
\|
= link_to 'Back', foos_path

app/views/foos/index.html.haml
%h1 Listing foos

%table
  %tr
    %th Bar
    %th
    %th
    %th

  - @foos.each do |foo|
    %tr
      %td= foo.bar
      %td= link_to 'Show', foo
      %td= link_to 'Edit', edit_foo_path(foo)
      %td= link_to 'Destroy', foo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Foo', new_foo_path

app/views/foos/new.html.haml
%h1 New foo

= render 'form'

= link_to 'Back', foos_path

app/views/foos/show.html.haml
%p#notice= notice

%p
  %b Bar:
  = @foo.bar

= link_to 'Edit', edit_foo_path(@foo)
\|
= link_to 'Back', foos_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secret</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Secret
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
  %body
    #header
      %h1
        Shhhhh!!!
    %hr
    #content
      = yield

app/views/welcome/index.html.haml
%h2 You can tell me...

%p
  %label 
    Enter a zecret message below. Nobody will be able to read it without the password.
    %br
    %textarea.zecret-input{ maxlength: "65536" }
%p
  %label
    Enter a password. This will be used to encrypt the zecret message.
    %br
    %input.password{ size: "100", maxlength: "64", type: "password" }
  %button.randomize Generate Random Password

= form_for @zecret do |f|
  = f.hidden_field :body
  .actions
    = f.submit "Encrypt New Zecret!"

%hr

%h2 Psst, don't tell anyone...

- if flash.alert
  .flash.alert= flash.alert

= form_tag retrieve_zecrets_path, method: "get" do
  #secret-id-field
    = label_tag :zecret_id, "Retrieve a zecret.  Enter the zecret's id# below:"
  = text_field_tag :zecret_id
  .actions
    = submit_tag "Get Zecret"

app/views/zecrets/show.html.haml
%h3= "ZECRET: "
.zecret-display
  %pre
    = @zecret.body
.zecret-hidden
  = @zecret.body

%p
  %label
    Enter Zecret password to decrypt the Zecret.
    %br
    %input.password{ size: "100", maxlength: "64", type: "password" }
  %button.decrypt Decrypt Zecret!
  
%p.zecret-id= "ZECRET ID: #{@zecret.id}"
%p= "Use this ID to retrieve this Zecret."